FROM node:16-alpine as builder

ARG REACT_APP_API_KEY
ARG REACT_APP_AUTH_DOMAIN
ARG REACT_APP_PROJECT_ID
ARG REACT_APP_MESSAGE_SENDER_ID
ARG REACT_APP_APP_ID
ARG REACT_APP_MEASUREMENT_ID

ENV REACT_APP_API_KEY $REACT_APP_API_KEY
ENV REACT_APP_AUTH_DOMAIN $REACT_APP_AUTH_DOMAIN
ENV REACT_APP_PROJECT_ID $REACT_APP_PROJECT_ID
ENV REACT_APP_MESSAGE_SENDER_ID $REACT_APP_MESSAGE_SENDER_ID
ENV REACT_APP_APP_ID $REACT_APP_APP_ID
ENV REACT_APP_MEASUREMENT_ID $REACT_APP_MEASUREMENT_ID

WORKDIR '/app'

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
EXPOSE 3000

# We will copy the whole ngninx config file into the empty config file of the nginx container
COPY ./default.conf /etc/nginx/conf.d/default.conf

# We will copy the build folder from the first react build at the top into the build folder the nginx
COPY --from=builder /app/build /usr/share/nginx/html