FROM node:16-alpine as builder

WORKDIR '/app'

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
EXPOSE 3000

# We will copy the whole ngninx config file into the empty config file of the nginx container
COPY ./default.conf /etc/nginx/conf.d/default.conf

# We will copy the build folder from the first react build at the top into the build folder the nginx
COPY --from=builder /app/build /usr/share/nginx/html