FROM node:14-alpine

ARG REACT_APP_API_KEY
ARG REACT_APP_AUTH_DOMAIN
ARG REACT_APP_PROJECT_ID
ARG REACT_APP_MESSAGE_SENDER_ID
ARG REACT_APP_APP_ID
ARG REACT_APP_MEASUREMENT_ID

ENV REACT_APP_API_KEY $REACT_APP_API_KEY
ENV REACT_APP_AUTH_DOMAIN $REACT_APP_AUTH_DOMAIN
ENV REACT_APP_PROJECT_ID $REACT_APP_PROJECT_ID
ENV REACT_APP_MESSAGE_SENDER_ID $REACT_APP_MESSAGE_SENDER_ID
ENV REACT_APP_APP_ID $REACT_APP_APP_ID
ENV REACT_APP_MEASUREMENT_ID $REACT_APP_MEASUREMENT_ID

# Change the working directory
WORKDIR /app

# Copy the package.json file
COPY package*.json ./

# Install all the modules if there is a change in previous step
RUN npm install

# Copy the rest of the folder
COPY . .

# Expose port 3000
EXPOSE 3000

# Create volume for the node_modules folder
VOLUME "/app/node_modules" 

# Start command
CMD ["npm", "start"]