version: "3.9"

services:
  api:
    build:
      context: ./simpleServer
      dockerfile: Dockerfile
    env_file:
      - ./simpleServer/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./simpleServer:/app
      - /app/node_modules

  socket:
    build:
      context: ./socketServer
      dockerfile: dockerfile
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./socketServer:/app
      - /app/node_modules
    ports:
      - "5001:5001"

  react-app:
    build:
      context: ./youtube2022
      dockerfile: dockerfile
    volumes:
      - ./youtube2022:/app
      - /app/node_modules
    depends_on:
      - api
      - socket
    networks:
      - app-network
    env_file:
      - ./youtube2022/.env

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - react-app
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - app-network
    logging:
      driver: "none"
networks:
  app-network:
