version: '3.9'

services:
  mongodb:
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  test-mongodb:
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null 
    volumes:
      - test_mongodb_data:/data/db  
    networks:
      - app-network
    ports:
      - "27018:27017"
    

  test:
    build: 
      context: .
      dockerfile: dockerfile.test
    environment:
      - DB_HOST=test-mongodb
      - DB_PORT=27017
    depends_on:
      - test-mongodb
    networks:
      - app-network
    volumes:
      - .:/app

  dev:
    build: 
      context: .
      dockerfile: dockerfile.dev
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

volumes:
  mongodb_data:
  test_mongodb_data:

networks:
  app-network: