name: Docker Image CI

# Control when the action will run
on:
  # Trigger when the workflow will run but only the master branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  # Test the nodejs server
  build_test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v2

      - name: Buld the test image
        run: docker-compose -f docker-compose-test.yaml build

      - name: test the server
        run: docker-compose -f docker-compose-test.yaml up --abort-on-container-exit

  push_to_Docker_Hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to docker hub

      - name: login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build react app
        run: docker build -t ndohjapan/chat-client ./youtube2022

      - name: Build server
        run: docker build -t ndohjapan/chat-server ./simpleServer

      - name: Build socket server
        run: docker build -t ndohjapan/chat-socket ./socketServer

      - name: Build nginx
        run: docker build -t ndohjapan/chat-nginx ./nginx

      - name: Push React app to docker hub
        run: docker push ndohjapan/chat-client

      - name: Push Server to docker hub
        run: docker push ndohjapan/chat-server

      - name: Push Socket app to docker hub
        run: docker push ndohjapan/chat-socket

      - name: Push Nginx app to docker hub
        run: docker push ndohjapan/chat-nginx

  deploy_to_Google_Compute_Engine:
    runs-on: ubuntu-latest

    # needs: [push_to_Docker_Hub]

    steps:
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          key: ${{secrets.GOOGLE_CLOUD_VM_SSH}}
          host: ${{secrets.GOOGLE_CLOUD_VM_IP}}
          username: ${{secrets.GOOGLE_CLOUD_VM_USERNAME}}
          script: |
            cd /var/app/docker-react-chat-app
            git pull
            sudo docker compose down
            sudo docker compose up --detach