name: Docker Image CI

# Control when the action will run
on:
  # Trigger when the workflow will run but only the master branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:

  # Test the nodejs server
  build_test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v2

      - name: Buld the test image
        run: docker-compose -f docker-compose-test.yaml --build

      - name: test the server
        run: docker-compose -f docker-compose-test.yaml up
  
  push_to_Docker_Hub:

    runs-on: ubuntu-latest

    needs: [build_test]

    steps: 

      - uses: actions/checkout@v3

      # Login to docker hub

      - name: login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        run: |
          docker-compose -f docker-compose-dev.yaml -t ndohjapan/chat-app --build
          docker-compose push ndohjapan/chat-app